//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_dem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public Товары()
        {
            this.Список_заказа = new HashSet<Список_заказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public Nullable<int> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }

        public string FullImagePath
        {
            get
            {
                if (string.IsNullOrEmpty(Фото)) Фото = "picture.png";
                return System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
                    "assets", Фото);
            }
        }

        public float Цена_со_скидкой
        {
            get
            {
                if (string.IsNullOrEmpty(Convert.ToString(Цена)) || 
                        string.IsNullOrEmpty(Convert.ToString(Действующая_скидка))) 
                    return 0;
                else
                {
                    float price = (float)Цена;
                    float discount = (float)Действующая_скидка;

                    return (float)price * (1 - (float) discount/100);
                }
            }
        }

        public virtual ICollection<Список_заказа> Список_заказа { get; set; }
    }
}
