//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prikaz2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagazinObuviEntities : DbContext
    {
        public MagazinObuviEntities()
            : base("name=MagazinObuviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Заказы> Заказы { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<Пункты_выдачи> Пункты_выдачи { get; set; }
        public DbSet<Список_заказа> Список_заказа { get; set; }
        public DbSet<Товары> Товары { get; set; }
    }
}
