//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prikaz2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public Заказы()
        {
            this.Список_заказа = new HashSet<Список_заказа>();
        }
    
        public int Номер_заказа { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<int> Адрес_пункта_выдачи { get; set; }
        public string ФИО_авторизированного_клиента { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public string Код_для_получения { get; set; }
        public string Статус_заказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
        public virtual ICollection<Список_заказа> Список_заказа { get; set; }
    }
}
