//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prikaz2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public Товары()
        {
            this.Список_заказа = new HashSet<Список_заказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public Nullable<int> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<Список_заказа> Список_заказа { get; set; }
    }
}
